### ISSUE TITLE
Error on .mcping

### ISSUE THREAD

**Issue by Favorlock** [CloudBotIRC/CloudBotLegacy#57]
This only happens the first time the command is typed as far as I can tell. I'm running on centos. The bot is up on irc.esper.net #OmniGamersNation.

The command will never ping a server.

Error:

Unhandled exception in thread started by <bound method Handler.start of <__main__.Handler object at 0x295f390>>
Traceback (most recent call last):
Unhandled exception in thread started by <bound method Handler.start of <__main__.Handler object at 0x2959090>>  File "core/main.py", line 98, in start

Traceback (most recent call last):
    db = bot.get_db_connection(input.conn)
  File "core/main.py", line 98, in start
  File "core/db.py", line 12, in get_db_connection
        name = '{}.db'.format(conn.name)
db = bot.get_db_connection(input.conn)
ValueError11:06:17 #omnigamersnation <Favorlock> .mcping mc.omnigamersnation.com
  File "core/db.py", line 12, in get_db_connection
:     zero length field name in format
name = '{}.db'.format(conn.name)
ValueError: zero length field name in format
ï¿½

Hope you can help.

**Comment by neoice** [comment]
I receive the same stack trace during startup. it occurs after the MOTD but before the "Bot ready" message.

Unhandled exception in thread started by <bound method Handler.start of <__main__.Handler object at 0x124b650>>
Traceback (most recent call last):
  File "core/main.py", line 98, in start
Unhandled exception in thread started by <bound method Handler.start of <__main__.Handler object at 0xf52fd0>>
Traceback (most recent call last):
  File "core/main.py", line 98, in start
        db = bot.get_db_connection(input.conn)
db = bot.get_db_connection(input.conn)
  File "core/db.py", line 12, in get_db_connection
  File "core/db.py", line 12, in get_db_connection
    name = '{}.db'.format(conn.name)
    ValueErrorname = '{}.db'.format(conn.name)
: zero length field name in formatValueError: zero length field name in format

from the looks of it, something tries to make a database connection even when the database is not configured.

**Comment by neoice** [comment]
I cannot repro this issue on .mcping, however _my_ stack track goes away if I change core/db.py L12: `{}.db` is not a valid filename.

**Comment by nasonfish** [comment]
I'm probably a little late here, but this is due to running the wrong version of python; CloudBot needs Python2.7 to run - see http://toomuchdata.com/2012/06/25/how-to-install-python-2-7-3-on-centos-6-2/

It doesn't need to configure a database, since it uses SQLite, it's just the way the database is being accessed is wrong.

Another way to prevent this error would be to change `'{}.db'.format(conn.name)` on line 12 of `core/db.py`, to `'%s.db' % conn.name`. I can't say this won't cause other errors in the future, since CloudBot is made for Python2.7, but it would fix this error temporarily.

This line is the plugin finding the correct database name to use, i.e. `EsperNet.db`.
